// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA6IWYURICvBEbtvEy5BYpvj2CFZ_G8VI',
    appId: '1:1023243723919:web:36fdd1cac0db9263007cfa',
    messagingSenderId: '1023243723919',
    projectId: 'mq-pay-fb',
    authDomain: 'mq-pay-fb.firebaseapp.com',
    storageBucket: 'mq-pay-fb.firebasestorage.app',
    measurementId: 'G-J2RYZTHEZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDStWD1MAzAf7tctkpP1yy26T55n0TsvtI',
    appId: '1:1023243723919:android:e3d9f7e141db24b7007cfa',
    messagingSenderId: '1023243723919',
    projectId: 'mq-pay-fb',
    storageBucket: 'mq-pay-fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2YPNmJjp-dQ9cPRMNdnXSESeRyz9pF80',
    appId: '1:1023243723919:ios:60e4f3b758f4e6f1007cfa',
    messagingSenderId: '1023243723919',
    projectId: 'mq-pay-fb',
    storageBucket: 'mq-pay-fb.firebasestorage.app',
    iosBundleId: 'com.example.mqPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2YPNmJjp-dQ9cPRMNdnXSESeRyz9pF80',
    appId: '1:1023243723919:ios:60e4f3b758f4e6f1007cfa',
    messagingSenderId: '1023243723919',
    projectId: 'mq-pay-fb',
    storageBucket: 'mq-pay-fb.firebasestorage.app',
    iosBundleId: 'com.example.mqPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA6IWYURICvBEbtvEy5BYpvj2CFZ_G8VI',
    appId: '1:1023243723919:web:2f0efab23ff41d2c007cfa',
    messagingSenderId: '1023243723919',
    projectId: 'mq-pay-fb',
    authDomain: 'mq-pay-fb.firebaseapp.com',
    storageBucket: 'mq-pay-fb.firebasestorage.app',
    measurementId: 'G-46TJV1HVP9',
  );
}
